"use client"

import { Icon } from "@/src/frontend/components/common/icon"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/src/frontend/components/ui/card"
import { motion } from "framer-motion"

export default function ServicesSection() {
  return (
    <section id="services" className="py-12 sm:py-16 md:py-20 bg-background">
      <div className="container px-4 sm:px-6 mx-auto">
        <div className="text-center max-w-3xl mx-auto mb-10 sm:mb-12 md:mb-16">
          <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold mb-3 sm:mb-4">
            Structured product documentation, generated by AI
          </h2>
          <div className="h-1 w-16 sm:w-20 bg-primary mx-auto mb-4 sm:mb-6"></div>
          <p className="text-base sm:text-lg text-muted-foreground px-4 sm:px-0">
            Prism turns a single idea into a complete, version-controlled documentation set that
            covers scope, requirements, delivery, and risk.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6 md:gap-8">
          {/* Project Brief */}
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }} viewport={{ once: true }}>
            <motion.div whileHover={{ y: -10, boxShadow: "0 10px 30px -15px rgba(48, 200, 201, 0.2)" }} className="h-full">
              <Card className="bg-card/50 border border-border backdrop-blur-sm hover:border-primary/50 transition-all duration-300 h-full">
                <CardHeader className="p-4 sm:p-6">
                  <div className="mb-3 sm:mb-4">
                    <Icon name="FileText" className="h-8 w-8 sm:h-10 sm:w-10 text-primary" />
                  </div>
                  <CardTitle className="text-lg sm:text-xl">Project Brief</CardTitle>
                </CardHeader>
                <CardContent className="p-4 sm:p-6 pt-0">
                  <CardDescription className="text-sm sm:text-base text-muted-foreground">
                    A canonical brief that defines the problem, target users, goals, constraints,
                    and success criteria.
                  </CardDescription>
                </CardContent>
              </Card>
            </motion.div>
          </motion.div>

          {/* Scope & Features */}
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.1 }} viewport={{ once: true }}>
            <motion.div whileHover={{ y: -10, boxShadow: "0 10px 30px -15px rgba(48, 200, 201, 0.2)" }} className="h-full">
              <Card className="bg-card/50 border border-border backdrop-blur-sm hover:border-primary/50 transition-all duration-300 h-full">
                <CardHeader className="p-4 sm:p-6">
                  <div className="mb-3 sm:mb-4">
                    <Icon name="ListChecks" className="h-8 w-8 sm:h-10 sm:w-10 text-primary" />
                  </div>
                  <CardTitle className="text-lg sm:text-xl">Scope & Features</CardTitle>
                </CardHeader>
                <CardContent className="p-4 sm:p-6 pt-0">
                  <CardDescription className="text-sm sm:text-base text-muted-foreground">
                    Clearly scoped features with explicit in-scope and out-of-scope decisions,
                    prioritized against real constraints.
                  </CardDescription>
                </CardContent>
              </Card>
            </motion.div>
          </motion.div>

          {/* Epics & Stories */}
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.2 }} viewport={{ once: true }}>
            <motion.div whileHover={{ y: -10, boxShadow: "0 10px 30px -15px rgba(48, 200, 201, 0.2)" }} className="h-full">
              <Card className="bg-card/50 border border-border backdrop-blur-sm hover:border-primary/50 transition-all duration-300 h-full">
                <CardHeader className="p-4 sm:p-6">
                  <div className="mb-3 sm:mb-4">
                    <Icon name="Kanban" className="h-8 w-8 sm:h-10 sm:w-10 text-primary" />
                  </div>
                  <CardTitle className="text-lg sm:text-xl">Epics & User Stories</CardTitle>
                </CardHeader>
                <CardContent className="p-4 sm:p-6 pt-0">
                  <CardDescription className="text-sm sm:text-base text-muted-foreground">
                    Structured epics and deduplicated user stories with clear acceptance criteria
                    and full traceability.
                  </CardDescription>
                </CardContent>
              </Card>
            </motion.div>
          </motion.div>

          {/* Roadmap */}
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.3 }} viewport={{ once: true }}>
            <motion.div whileHover={{ y: -10, boxShadow: "0 10px 30px -15px rgba(48, 200, 201, 0.2)" }} className="h-full">
              <Card className="bg-card/50 border border-border backdrop-blur-sm hover:border-primary/50 transition-all duration-300 h-full">
                <CardHeader className="p-4 sm:p-6">
                  <div className="mb-3 sm:mb-4">
                    <Icon name="Calendar" className="h-8 w-8 sm:h-10 sm:w-10 text-primary" />
                  </div>
                  <CardTitle className="text-lg sm:text-xl">Roadmap</CardTitle>
                </CardHeader>
                <CardContent className="p-4 sm:p-6 pt-0">
                  <CardDescription className="text-sm sm:text-base text-muted-foreground">
                    An editable roadmap that translates scope and stories into milestones
                    and delivery phases.
                  </CardDescription>
                </CardContent>
              </Card>
            </motion.div>
          </motion.div>

          {/* Export */}
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.4 }} viewport={{ once: true }}>
            <motion.div whileHover={{ y: -10, boxShadow: "0 10px 30px -15px rgba(48, 200, 201, 0.2)" }} className="h-full">
              <Card className="bg-card/50 border border-border backdrop-blur-sm hover:border-primary/50 transition-all duration-300 h-full">
                <CardHeader className="p-4 sm:p-6">
                  <div className="mb-3 sm:mb-4">
                    <Icon name="Download" className="h-8 w-8 sm:h-10 sm:w-10 text-primary" />
                  </div>
                  <CardTitle className="text-lg sm:text-xl">Export & Share</CardTitle>
                </CardHeader>
                <CardContent className="p-4 sm:p-6 pt-0">
                  <CardDescription className="text-sm sm:text-base text-muted-foreground">
                    Export documentation to Markdown, PDF, or DOCX for easy sharing
                    with stakeholders and partners.
                  </CardDescription>
                </CardContent>
              </Card>
            </motion.div>
          </motion.div>

          {/* Secure & Owned */}
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.5 }} viewport={{ once: true }}>
            <motion.div whileHover={{ y: -10, boxShadow: "0 10px 30px -15px rgba(48, 200, 201, 0.2)" }} className="h-full">
              <Card className="bg-card/50 border border-border backdrop-blur-sm hover:border-primary/50 transition-all duration-300 h-full">
                <CardHeader className="p-4 sm:p-6">
                  <div className="mb-3 sm:mb-4">
                    <Icon name="ShieldCheck" className="h-8 w-8 sm:h-10 sm:w-10 text-primary" />
                  </div>
                  <CardTitle className="text-lg sm:text-xl">Versioned & Owned</CardTitle>
                </CardHeader>
                <CardContent className="p-4 sm:p-6 pt-0">
                  <CardDescription className="text-sm sm:text-base text-muted-foreground">
                    OAuth authentication, explicit ownership, and full version history with
                    review and apply control.
                  </CardDescription>
                </CardContent>
              </Card>
            </motion.div>
          </motion.div>
        </div>
      </div>
    </section>
  )
}
